# Generated by Django 5.0 on 2023-12-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogtraining', '0002_dog_age_dog_creation_date_dog_owners_alter_dog_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
